## Numpy Array Operations

In [1]:
import numpy as np

In [3]:
arr = np.arange(1, 11)
print("Basic slicing: ", arr[2:7])
print("With Step: ", arr[1:8:2])

Basic slicing:  [3 4 5 6 7]
With Step:  [2 4 6 8]


In [10]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("Speciifc element: ", arr_2d[1, 2])
print("Entire row: ", arr_2d[0])
print("Entire column: ", arr_2d[:,2])

Speciifc element:  6
Entire row:  [1 2 3]
Entire column:  [3 6]


## Sorting

In [15]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1,2], [2, 3]])
print("Sorted 2d array by column: ", np.sort(arr_2d_unsorted, axis=1))

Sorted Array:  [1 1 2 3 4 5 6 9]
Sorted 2d array by column:  [[1 3]
 [1 2]
 [2 3]]


## Filter


In [16]:
numbers = np.arange(11)
even_number = numbers[numbers % 2 == 0]
print("Even numbers: ", even_number)

Even numbers:  [ 0  2  4  6  8 10]


## Filter with mask

In [17]:
mask = numbers > 5
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [20]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where: ", numbers[where_result])

[0 2 4]
(array([ 6,  7,  8,  9, 10]),)
NP where:  [ 6  7  8  9 10]


In [28]:
condition_array = np.where(numbers > 5)
print(condition_array)

condition_array = np.where(numbers > 5, numbers*4, numbers)
print(condition_array)

(array([ 6,  7,  8,  9, 10]),)
[ 0  1  2  3  4  5 24 28 32 36 40]


### Adding and removing data

In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Array Compatibility

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8 , 9])

print("Compatibility check: ", a.shape == b.shape)

Compatibility check:  True


In [36]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [38]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)

print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]
