## Numpy array and basics

In [2]:
import numpy as np

## Creating array from a list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


## List vs numpy array


In [ ]:
py_list = [1, 2, 3]
print("Python list multiplication: ", py_list * 2)

np_array = np.array([1,2,3]) #element wise multiplication
print("Python array multiplication: ", np_array * 2)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]


In [ ]:
import time

start = time.time()
py_list = [i*2 for i in range(1000000000000)]
print("List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000000000) * 2
print("Numpy operation time: ", time.time() - start)

## Creating array from scratch

In [5]:
zeros = np.zeros((3,4))
print("Zeros array: \n", zeros)

ones = np.ones((3,4))
print("Ones array: \n", ones)

random = np.random.random((2,3))
print("Random array: \n", random)


sequence = np.arange(0,10,2)
print("Sequence array: \n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random array: 
 [[0.57548889 0.22148293 0.2576891 ]
 [0.37607436 0.06089057 0.70319183]]
Sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [6]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor: ", tensor)


Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DType: ", arr.dtype)


Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int64


## Array Reshaping


In [8]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array: ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array: ", flattened)

# ravel returns view, insetead of copy
raveled = reshaped.ravel()
print("\n raveled array: ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array: ", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
